-- MySQL Script generated by MySQL Workbench
-- ven. 16 avril 2021 07:18:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema voilier1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema voilier1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `voilier1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `voilier1` ;

-- -----------------------------------------------------
-- Table `voilier1`.`Personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voilier1`.`Personne` (
  `idPersonne` INT NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Age` INT NULL DEFAULT NULL,
  `Salaire` FLOAT NULL DEFAULT NULL,
  `Equipage` VARCHAR(45) NULL DEFAULT NULL,
  `Sponsors` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idPersonne`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `voilier1`.`Voilier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voilier1`.`Voilier` (
  `idVoilier` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `NbrPlace` INT NULL DEFAULT NULL,
  `Prix` FLOAT NULL DEFAULT NULL,
  `Marque` VARCHAR(45) NULL DEFAULT NULL,
  `Vitesse` FLOAT NULL DEFAULT NULL,
  `Poids` FLOAT NULL DEFAULT NULL,
  `Latitude` DOUBLE NULL DEFAULT NULL,
  `Longitude` DOUBLE NULL DEFAULT NULL,
  `Personne_idPersonne` INT NOT NULL,
  PRIMARY KEY (`idVoilier`),
  INDEX `fk_Voilier_Personne1_idx` (`Personne_idPersonne` ASC) VISIBLE,
  CONSTRAINT `fk_Voilier_Personne1`
    FOREIGN KEY (`Personne_idPersonne`)
    REFERENCES `voilier1`.`Personne` (`idPersonne`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `voilier1`.`Penalite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voilier1`.`Penalite` (
  `idPenalite` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Duree` TIME NOT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idPenalite`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `voilier1`.`VoilierEtape`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voilier1`.`VoilierEtape` (
  `idVoilierEtape` INT NOT NULL,
  `Duree` DATETIME NOT NULL,
  `Penalite_idPenalite` INT NOT NULL,
  `Voilier_idVoilier` INT NOT NULL,
  `DateDebut` DATETIME NOT NULL,
  `DateFIn` DATETIME NOT NULL,
  PRIMARY KEY (`idVoilierEtape`),
  INDEX `fk_VoilierEtape_Penalite1_idx` (`Penalite_idPenalite` ASC) VISIBLE,
  INDEX `fk_VoilierEtape_Voilier1_idx` (`Voilier_idVoilier` ASC) VISIBLE,
  CONSTRAINT `fk_VoilierEtape_Penalite1`
    FOREIGN KEY (`Penalite_idPenalite`)
    REFERENCES `voilier1`.`Penalite` (`idPenalite`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_VoilierEtape_Voilier1`
    FOREIGN KEY (`Voilier_idVoilier`)
    REFERENCES `voilier1`.`Voilier` (`idVoilier`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `voilier1`.`Etape`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voilier1`.`Etape` (
  `idEtape` INT NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `DateDebut` DATETIME NOT NULL,
  `DateFIn` DATETIME NOT NULL,
  `VoilierEtape_idVoilierEtape` INT NOT NULL,
  `Voilier_idVoilier` INT NOT NULL,
  PRIMARY KEY (`idEtape`),
  INDEX `fk_Etape_VoilierEtape1_idx` (`VoilierEtape_idVoilierEtape` ASC) VISIBLE,
  INDEX `fk_Etape_Voilier1_idx` (`Voilier_idVoilier` ASC) VISIBLE,
  CONSTRAINT `fk_Etape_Voilier1`
    FOREIGN KEY (`Voilier_idVoilier`)
    REFERENCES `voilier1`.`Voilier` (`idVoilier`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Etape_VoilierEtape1`
    FOREIGN KEY (`VoilierEtape_idVoilierEtape`)
    REFERENCES `voilier1`.`VoilierEtape` (`idVoilierEtape`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `voilier1`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voilier1`.`Course` (
  `idCourse` INT NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Etape_idEtape` INT NOT NULL,
  `DureeCumuleBrute` DATETIME NULL DEFAULT NULL,
  `DureeCumuleReel` DATETIME NULL DEFAULT NULL,
  `VoilierEtape_idVoilierEtape` INT NOT NULL,
  `Voilier_idVoilier` INT NOT NULL,
  PRIMARY KEY (`idCourse`),
  INDEX `fk_Course_Etape_idx` (`Etape_idEtape` ASC) VISIBLE,
  INDEX `fk_Course_VoilierEtape1_idx` (`VoilierEtape_idVoilierEtape` ASC) VISIBLE,
  INDEX `fk_Course_Voilier1_idx` (`Voilier_idVoilier` ASC) VISIBLE,
  CONSTRAINT `fk_Course_Etape`
    FOREIGN KEY (`Etape_idEtape`)
    REFERENCES `voilier1`.`Etape` (`idEtape`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Course_Voilier1`
    FOREIGN KEY (`Voilier_idVoilier`)
    REFERENCES `voilier1`.`Voilier` (`idVoilier`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Course_VoilierEtape1`
    FOREIGN KEY (`VoilierEtape_idVoilierEtape`)
    REFERENCES `voilier1`.`VoilierEtape` (`idVoilierEtape`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
